global:
  # scrape_interval: 1m
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'traefik'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'grainjs'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.64.1:3102', '192.168.64.1:3001']

# Если вы хотите собирать метрики напрямую с Jaeger (опционально)
# - job_name: 'jaeger'
#   static_configs:
#     - targets: ['jaeger:16686'] # Jaeger UI /metrics endpoint