{
 "title": "Grain Exporter Full",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   },
   {
    "name": "env",
    "label": "db",
    "query": {
     "query": "label_values(mongodb_connections,instance)"
    }
   },
   {
    "name": "telemetrySource",
    "label": "App",
    "query": {}
   },
   { "name": "reqDuration", "label": "Duration(latency)", "query": "1s,5s,15s,30s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "Long running Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "41c94686", "operator": "=", "scope": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "$reqDuration",
       "valueType": "duration"
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$telemetrySource" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "MongoDB sessions in mongoose",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grainjs_server_mongoose_open_connections_total",
     "legendFormat": "Open sessions"
    },
    {
     "expr": "grainjs_server_mongoose_active_sessions_total",
     "legendFormat": "Active sessions"
    }
   ]
  },
  {
   "title": "Connections Created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "grainjs_server_mongoose_connections_created_total{instance=~\"$instance\"}",
     "legendFormat": "{{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Grainjs request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "irate(grainjs_server_response_time_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"current\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "mongodb_connections{instance=~\"$env\",state=\"active\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  }
 ]
}